/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;

import com.sun.jmx.snmp.BerDecoder;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author komputer
 */
public class transaksi extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public Connection cn = config.koneksi.getKoneksi();
    public DefaultTableModel tabmodel;
    public Date hariini = new Date();
    public SimpleDateFormat format = new SimpleDateFormat("Y-MM-dd");
    public String hari = format.format(hariini);
    public int sub;
    public static String iduser;
    
    public void judul(){
        Object[] judul ={"Kode Pesanan","Atas Nama","No.HP","NO.Meja","Total","Tanggal Pesanan","status"};
        tabmodel = new DefaultTableModel(null, judul);
        tbl_pesanan.setModel(tabmodel);
    }
    
    public void tampildata(){
         try {
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tbl_pesanan WHERE status = '0'");
            while (rs.next()) {
                Object[] data = {
                    rs.getString("kd_pesanan"),
                    rs.getString("atas_nama"),
                    rs.getString("no_hp"),
                    rs.getString("no_meja"),
                    rs.getInt("total"),
                    rs.getDate("tanggal_pesanan"),
                    rs.getInt("status")
                };tabmodel.addRow(data);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void refresh(){
        tampildata();
        lkode.setText("");
        lnama.setText("");
        lmeja.setText("");
        ltotal.setText("");
        lkembali.setText("");
    }
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        judul();
        tampildata();
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pesanan = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tbayar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lkembali = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lmeja = new javax.swing.JLabel();
        lkode = new javax.swing.JLabel();
        lnama = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        bbayar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(85, 153, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_pesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pesanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 750, 460));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(232, 146, 61));
        jLabel18.setText("NO.MEJA      :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(232, 146, 61));
        jLabel13.setText("BAYAR     :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        tbayar.setBackground(new java.awt.Color(85, 153, 142));
        tbayar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tbayar.setForeground(new java.awt.Color(255, 255, 255));
        tbayar.setBorder(null);
        tbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbayarKeyTyped(evt);
            }
        });
        jPanel1.add(tbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 410, 60));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 146, 61));
        jLabel15.setText("KEMBALI :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        lkembali.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lkembali.setForeground(new java.awt.Color(255, 255, 255));
        lkembali.setText("1000000");
        jPanel1.add(lkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(232, 146, 61));
        jLabel20.setText("KODE            :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        lmeja.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lmeja.setForeground(new java.awt.Color(232, 146, 61));
        lmeja.setText("A001");
        jPanel1.add(lmeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        lkode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lkode.setForeground(new java.awt.Color(232, 146, 61));
        lkode.setText(" ");
        jPanel1.add(lkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        lnama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lnama.setForeground(new java.awt.Color(232, 146, 61));
        lnama.setText("ZIDUN");
        jPanel1.add(lnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(74, 131, 122));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(232, 146, 61));
        jLabel22.setText("ATAS NAMA  :");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 560, 180));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Daftar Pesanan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 420, 10));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(232, 146, 61));
        jLabel23.setText("TOTAL     :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        ltotal.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ltotal.setForeground(new java.awt.Color(255, 255, 255));
        ltotal.setText("1000000");
        jPanel1.add(ltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        bbayar.setBackground(new java.awt.Color(74, 131, 122));
        bbayar.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        bbayar.setText("BAYAR");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });
        jPanel1.add(bbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 390, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 1380, 730));

        jPanel2.setBackground(new java.awt.Color(74, 131, 122));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Daftar Pesanan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORM TRANSAKSI");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 40));

        close.setBackground(new java.awt.Color(74, 131, 122));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        close.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void tbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbayarKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (! ((Character.isDigit(c) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_TAB) ))){
            evt.consume();
        }
    }//GEN-LAST:event_tbayarKeyTyped

    private void tbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbayarKeyReleased
        // TODO add your handling code here:
        int bayar = Integer.parseInt(tbayar.getText());
        sub = Integer.parseInt(ltotal.getText());
        if (bayar == 0 || bayar < sub) {
            lkembali.setText("Rp. 0");
        }else{
            int kembali = bayar - sub;
            lkembali.setText("Rp. "+String.valueOf(kembali));
        }
    }//GEN-LAST:event_tbayarKeyReleased

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void tbl_pesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pesananMouseClicked
        // TODO add your handling code here:
        lkode.setText(tabmodel.getValueAt(tbl_pesanan.getSelectedRow(), 0)+"");
        lnama.setText(tabmodel.getValueAt(tbl_pesanan.getSelectedRow(), 1)+"");
        lmeja.setText(tabmodel.getValueAt(tbl_pesanan.getSelectedRow(), 3)+"");
        ltotal.setText(tabmodel.getValueAt(tbl_pesanan.getSelectedRow(), 4)+"");
        
    }//GEN-LAST:event_tbl_pesananMouseClicked

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        // TODO add your handling code here:
        if(tbayar.getText().isEmpty() || tbayar.getText().equals(0)){
            JOptionPane.showMessageDialog(null, "Lengkapi Data");
        }else{
            try {
                st = cn.createStatement();
                st.executeUpdate("INSERT INTO tbl_transaksi VALUES(null,'"+lkode.getText()+"','"+iduser+"','"+ltotal.getText()+"','"+tbayar.getText()+"','"+lkembali.getText()+"','"+hari+"',null)");
                JOptionPane.showMessageDialog(null, "Transaksi Selesai");
                refresh();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        iduser=args[0];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbayar;
    private javax.swing.JPanel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lkembali;
    private javax.swing.JLabel lkode;
    private javax.swing.JLabel lmeja;
    private javax.swing.JLabel lnama;
    private javax.swing.JLabel ltotal;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTable tbl_pesanan;
    // End of variables declaration//GEN-END:variables
}
